### ISSUE TITLE
CRUD Pembelian

### ISSUE THREAD

**Issue by dvrg** [wirasakti30/dev#11]
Template on progress... butuh trigger di database, aku yang buat ya luk...

**Comment by dvrg** [comment]
data dari module ini, pas di klik tambah data pembelian (detail_pembelian) otomatis akan menyimpan data id user ke database memancing trigger untuk menggenerate kode_invoice yang dibuat dr trigger. nah yg jadi pr adalah, setelah data tersimpan, kita harus ambil id pembelian agar bisa di pakai di detail pembelian, jadi seluruh data yang ditambahkan di detail pembelian akan menggunakan id pembelian yang sama.

**Comment by wirasakti30** [comment]
> data dari module ini, pas di klik tambah data pembelian (detail_pembelian) otomatis akan menyimpan data id user ke database memancing trigger untuk menggenerate kode_invoice yang dibuat dr trigger. nah yg jadi pr adalah, setelah data tersimpan, kita harus ambil id pembelian agar bisa di pakai di detail pembelian, jadi seluruh data yang ditambahkan di detail pembelian akan menggunakan id pembelian yang sama.

bukannya ini yang semalem aku buat ya pak, coba cek deh sama ga persepi ku dengan mu wkwkkw

**Comment by dvrg** [comment]
Revisi ya mas @wirasakti30,  alurnya kebalik, pertama tambah data barang dan alat dulu, baru dilakukan pembelian
- Yang di inputkan hanya nama barang, kuantitas, kategori barang serta supplier (harga dan tanggal dihapus, tanggal otomatis saat data tersimpan, nama barang otomastis juga select dari data alat dan bahan baku (pakek select option aja gpp))
- Trigger jumlah kuantitas barang ototmatis nambah dari pembelian
