### ISSUE TITLE
CRUD Penjualan

### ISSUE THREAD

**Issue by dvrg** [wirasakti30/dev#15]
Alur pembelian
- login
- pilih data rumah yang mau dijual
- inputkan data pemilik, blok
- data rumah berubah statusnya jadi terjual

**Comment by dvrg** [comment]
tambah data, gagal di option value, mohon di cek ya @wirasakti30

**Comment by wirasakti30** [comment]
> tambah data, gagal di option value, mohon di cek ya @wirasakti30

![done](https://user-images.githubusercontent.com/33976471/57262398-0272e400-7096-11e9-801c-7c9ae1c0030e.PNG)
